export default {
  index: 'Introduction',
  'getting-started': 'Getting Started',
  'local-dev': 'Local Dev Emulator',
  architecture: 'Architecture',
  contracts: {
    title: 'Contracts',
    type: 'separator',
  },
  'contract-api': 'Contract API',
  'contract-upgrades': 'Contract Upgrades',
  'sdk-reference': 'SDK Reference',
  'sdk-errors': 'SDK Error Reference',
  troubleshooting: 'Troubleshooting',
  guides: 'Guides',
  cookbook: 'Cookbook',
  'agent-integration': 'Agent Integration',
  security: 'Security',
  'threat-model': 'Threat Model',
}
